[package]
authors = ["TatriX <tatrics@gmail.com>"]
name = "hello-rocket"
version = "0.1.0"

[dependencies]
rocket = "0.3.3"
rocket_codegen = "0.3.3"
rocket_contrib = "0.3.3"
rocket_cors = "0.2.1"
serde = "1.0.20"
serde_derive = "1.0.20"
serde_json = "1.0.6"
